dmg_stun = readfloat(tagdata + 0x1E4) 
dmg_maximum_stun = readfloat(tagdata + 0x1E8)
dmg_stun_time = readfloat(tagdata + 0x1EC)
unit_stun_amount = readfloat(m_unit + 0x424)
unit_stun_timer = readword(m_unit + 0x428)
