-- Complete list of commands (and command aliases for Bumpercarz)
-- Type "/help <command name>" and it will show information about that command. 


rconadd(aliases: "addrcon")
adminadd(aliases: "a", "addadmin")
admindel(aliases: "deladmin", "revoke", "a del", "adminrevoke", "revokeadmin")
setafk(aliases: "afk")
adminlist(aliases: "admins", "listadmins", "alist")
alias(aliases: "alias")
remotecontrol(aliases:none)
anticaps(aliases: "disablecaps", "nocaps")
chatcommands(aliases:none)
chatids(aliases: "chatid", "showplayernumbers")
crouchcamo(aliases: "tigermode", "ninja", "ninjamode")
uniquesenabled(aliases: "uniqueplayercounting")
deathless(aliases: "deathlessplayer", "deathlessmode", "cheatdeathlessplayer")
falldamage(aliases:none)
firstjoinmessage(aliases:none)
centralbanlist(aliases: "centralbansystem", "remotebansystem", "remotebanlist", "globalbansystem", "globalbanlist", "masterbansystem", "masterbanlist")
hashduplicates(aliases:none)
infiniteammo(aliases: "infammo")
killspree(aliases: "killingspree")
multiteamvehicles(aliases:none)
noweapons(aliases:none)
pmenabled(aliases: "pvtmessage", "privatemessage")
rtvenabled(aliases:none)
serveradminmessage(aliases: "samessage")
scrimmode(aliases:none)
tbagdet(aliases: "tbagdetection")
votekickenabled(aliases:none)
defaultspawnweapons(aliases: "spawnweapons", "weaponsonspawn", "chooseweapons", "selectweapons", "poontang")
welcomebackmessage(aliases: "wbmessage")
adminblocker(aliases:none)
antispam(aliases:none)
balance(aliases:none)
banpenalty(aliases:none)
ban(aliases: "hashban", "b", "playerban", "banplayer")
bos(aliases:none)
kickbansfile(aliases:none)
commandsfile(aliases:none)
adminfile(aliases:none)
sharedhashfile(aliases:none)
banlistfile(aliases:none)
hashbanlist(aliases:none)
ipbanlist(aliases:none)
namebanlist(aliases:none)
textbanlist(aliases:none)
banlist(aliases: "listbans", "bans", "showbans", "viewbans")
unban(aliases: "ipunban", "hashunban", "textunban", "nameunban")
boslist(aliases:none)
bosplayers(aliases: "bosableplayers")
changelevel(aliases: "adminlevel", "levelchange", "level", "modifylevel", "changeadminlevel", "modifyadminlevel")
changeteam(aliases: "ts", "teamchange", "swapteam", "teamswap")
disconnect(aliases: "losenetworkconnection", "loseconnection", "dc")
count(aliases: "uniques", "uniqueplayers")
commands(aliases: "cmds", "commandlist", "list", "listcommands", "showcommands", "allcommands", "getcommands", "viewcommands")
crash(aliases:none)
damage(aliases: "dmg", "setdmg", "setdmgmulti", "setdamage")
delrcon(aliases: "rcondel")
eject(aliases: "playereject", "ejectplayer")
gethash(aliases: "hash", "gethash")
getip(aliases:none)
getloc(aliases: "getplayerlocation", "getplayerloc", "getplayercoords", "getcoords", "coords", "playerloc", "playercoords")
setgod(aliases: "god", "godmode", "godset", "cheatgod", "cheatsetgod", "cheatgodmode", "cheatinvincible", "invincible")
cheathax(aliases: "hax", "haxolu", "haxor", "1337")
heal(aliases: "healplayer", "playerheal", "cheatheal", "restorehealth", "cheatrestorehealth", "cheatheal")
hide(aliases: "hideplayer", "playerhide", "cheathide")
info(aliases: "i", "playerinfo", "infoplayer", "getplayerinfo", "getinfo")
ipban(aliases: "banip", "ipbanplayer")
invis(aliases: "camo", "camouflage", "setcamo", "cheatsetcamo", "cheatcamo", "cheatgivecamo", "givecamo")
kick(aliases: "k", "kickplayer", "playerkick")
kill(aliases: "killplayer", "playerkill", "cheatkill", "cheatkillplayer")
launch(aliases:none)
lo3(aliases: "scrim", "startscrim")
login(aliases: "l", "log")
mnext(aliases: "mapnext")
reset(aliases: "mapreset", "resetmap")
move(aliases: "j", "mv")
nameban(aliases: "banname")
overshield(aliases: "os", "giveos", "osgive", "giveovershield", "overshieldgive", "cheatgiveos", "cheatosgive", "cheatovershield", "cheatplayerovershield", "cheatgiveovershield", "cheatovershieldgive")
players(aliases: "pl", "playerlist")
playersmore(aliases: "plmore", "moreplayers")
privatesay(aliases: "pvtsay", "psay", "sayprivately")
rconlist(aliases: "listrcons", "rcons")
read(aliases:none)
write(aliases:none)
resetplayer(aliases: "playerreset", "playereset")
resetweapons(aliases:none)
resp(aliases: "respplayer", "playerresp")
rtvrequired(aliases: "rtvneeded", "totalrtv", "rtvtotal", "rtvpercent", "rtvpercentage", "rockthevoteneeded", "rockthevotepercent", "rockthevotetotal", "totalrockthevote", "midgamevoteneeded")
rtvtimeout(aliases: "rockthevotetimeout")
setammo(aliases: "ammo", "setammo", "ammoset")
setcolor(aliases: "color", "colorset", "playercolor", "cheatsetcolor", "cheatplayercolor")
setassists(aliases: "assists", "assistset", "setassists", "setassist")
setdeaths(aliases: "deaths", "deathset", "setdeaths", "setdeath")
setkills(aliases: "kills", "killset")
setscore(aliases: "scores", "score", "scoreset")
setupright(aliases:none)
setfrags(aliases: "setfrags", "frags", "fragset", "setfragnades")
setplasmas(aliases: "setplasmas", "stickies", "plasmas", "plasmaset", "setplasmanades")
setprefix(aliases: "serverprefix")
setmode(aliases: "modeset")
pass(aliases: "setpass", "password", "setpassword")
reloadadmins(aliases: "reloadadminlist", "adminlistreload", "adminsreload")
loadbanlist(aliases: "banlistload", "loadbans", "bansload", "mergebans", "bansmerge", "mergebanlist", "banlistmerge")
reloadbanlist(aliases: "banlistreload", "reloadbans", "bansreload", "refreshipbans")
respawntime(aliases: "setresp", "setrespawntime")
setspeed(aliases: "spd", "s", "speed", "speedset")
setteleport(aliases: "teleportadd", "addteleport", "tadd", "st", "tpadd", "addtp", "addlocation", "locationadd")
teleportlist(aliases: "tlist", "listteleports", "locations", "teleports", "locs")
spawn(aliases: "spawnobj", "create", "createobject", "spawnobject", "objspawn")
enter(aliases: "entervehicle", "vehicleeneter", "vehienter", "entervehi")
give(aliases: "giveweapon", "weapongive", "cheatgiveweapon")
spammax(aliases: "smax", "maxspam")
spamtimeout(aliases: "timeoutspam")
specs(aliases: "serverspecs", "machineinfo")
mc(aliases: "mcbegin", "startcycle", "cyclestart", "mapcyclebegin")
statusmore(aliases: "serverinfo", "sinfo", "sinfo")
superban(aliases: "ultraban", "megaban")
suspend(aliases: "suspendplayer", "playersuspend", "suspendpl", "sleep", "cheatsuspendplayer")
unsuspend(aliases: "unsuspendplayer", "unsuspendpl", "playerunsuspend")
takeweapons(aliases: "removeweapons", "takeweaponspl", "takeweps")
teleportdel(aliases: "tdel", "delteleport", "dellocation", "locationdel", "tpdel", "rmtel", "teldel", "deltel")
teleport(aliases: "tp", "t", "teletolocation", "tele")
textban(aliases: "mute", "muteplayer", "textbanplayer", "tban", "chatban", "playermute")
timecur(aliases: "curtime")
unbos(aliases: "removebos", "bosremove", "unbanbos", "bosunban")
ungod(aliases: "unsetgod", "removegod", "godunset", "godremove", "cheatunsetgod", "cheatremovegod", "cheatremovegodmode")
cheatunhax(aliases: "unhax")
unhide(aliases: "removehide", "cheatunhide", "cheatunhideplayer")
uninvis(aliases: "uncamo", "removeinvis", "removecamo", "cheatuncamoplayer", "cheatuninvis", "cheatremovecamo", "cheatuncamo", "cheatuncamoplayer")
unmute(aliases: "removemute")
viewadmins(aliases: "curadmins", "adminscur")
votekick_action(aliases: "votekickaction")
votekicktimeout(aliases:none)
votekickrequired(aliases: "votekickneeded")
